const listaBlogs = () => ([
  {
    title: 'No abras una tienda física si no tienes una experiencia de marca que brindar',
    img: 'New-apple-store-singapur.jpg',
    excerpt: 'En el libro “El ADN secreto de Amazon, Apple, Facebook y Google” Scott Galloway explica cómo el éxito de Apple se debió a la apertura de...',
    url: 'no-abras-una-tienda-física-si-no-tienes-una-experiencia-de-marca-que-brindar',
    fecha: '31 de agosto del 2020',
    content: 'En el libro “El ADN secreto de Amazon, Apple, Facebook y Google” Scott Galloway explica cómo el éxito de Apple se debió a la apertura de tiendas físicas en un momento en el que las empresas de teléfonos celulares estaban apostando por la venta digital. Incluso muchos vaticinaban el fracaso de la marca por escoger ese canal de venta tan corriente. Sin embargo la historia demostró lo contrario, Apple se volvió la empresa más valiosa del mundo y hasta el día de hoy la compañía de la manzana sigue apostando por abrir tiendas cada vez más espectaculares como la nueva tienda de Marina Bay Sands en Singapur.<br><br>![](/static/cef9b00871016b5bad317c7cae14430f/a6974/New-apple-store-singapur.jpg)<br><br>¿Significa entonces que mi marca debe apostar por abrir cientos de tiendas espectaculares? Si lo único que tienes para ofrecer es un producto, no lo hagas. Existen canales de venta mucho más económicos para vender pero solo uno para brindar una verdadera experiencia de marca.Esto se genera únicamente con una marca sólida y bien estructurada y en el canal digital muy pocas lo son.<br><br>Con la llegada del Covid-19, el sector minorista sufrió un golpe muy fuerte que dejó tambaleando a muchas marcas y noqueó a otras. Se habla de una aceleración hacia la digitalización pero poco se habla de la transformación de los espacios en esta nueva forma de consumo.<br><br>De los cientos de miles de locales que hay en el país, son realmente muy pocas las marcas que cuentan con una tienda memorable y en general pertenecen a compañías extranjeras respaldadas por un desarrollo de marca consolidado, las demás (con algunas excepciones) solo tienen un espacio en el que ponen sus productos a la espera de ser comprados, no ofrecen ninguna experiencia y su diseño es tan estandarizado que perfectamente se pueden confundir con cualquier otra marca.<br><br>Hoy, con todo lo que ha sucedido en el mundo del retail, abrir una tienda física sin una estrategia de marca robusta, un diseño que refleje al 100% el ADN de la marca y un mínimo de innovación que involucre tecnología y calor humano sería un suicidio para la rentabilidad de la empresa.'
  }
])

module.exports = { listaBlogs }
